#!/usr/bin/env bash
rm -rf serv
mkdir serv
mkdir serv/code
mkdir serv/worlds
cp -r lib blocks.py serv/code
cp serv.py serv/code
echo "#!/usr/bin/env bash
python3 code/serv.py" > serv/run
chmod u+x serv/run
